version: '3.5'

networks:     # custom default network name, https://github.com/docker/compose/pull/5448
  default:
    name: avalon_network

services:
  avalon-client:
    build: ./client-ng
    image: lujason/avalon/client
    ports:
      - '80:80'
    depends_on:
      - avalon-server

  avalon-server:
    build: ./algorithm-server
    image: lujason/avalon/server
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: avalon-mongodb:27017
    depends_on:
      - avalon-mongodb


  avalon-mongodb:
    image: mongo
    working_dir: ${PWD}
    volumes:
      - ${PWD}/data:/data/db
    ports:
      - '27017:27017'
